import { mkdirSync, writeFileSync } from "fs";
import { dirname } from "path";
import ts from "typescript";
import { exported, symbolType } from "./symbols";
import type { TypegenResult } from "./typegen";

/** Expand wire types into standalone declarations; never import a server module. */
function wireType(checker: ts.TypeChecker, type: ts.Type, node: ts.Node, seen = new Set<ts.Type>(), input = false,
    position: "response" | "property" | "array" | "body" | "query" = "response"): string {
    if (seen.has(type) || seen.size > 30) return "unknown";
    const next = new Set([...seen, type]);
    if (type.isUnion()) return type.types.map(member => wireType(checker, member, node, next, input, position)).join(" | ");
    if (type.isLiteral()) return JSON.stringify(type.value);
    if (type.flags & ts.TypeFlags.BooleanLiteral) return checker.typeToString(type);
    // JSON omits object fields but turns array slots into null. On input, exclude
    // undefined slots rather than claiming the schema accepts their null encoding.
    if (type.flags & (ts.TypeFlags.Undefined | ts.TypeFlags.Void)) {
        return position === "array" ? input ? "never" : "null" : "undefined";
    }
    // Express sends top-level null as an empty body; nested null stays JSON null.
    if (type.flags & ts.TypeFlags.Null) return !input && position === "response" ? "undefined" : "null";
    for (const [flag, text] of [[ts.TypeFlags.String, "string"], [ts.TypeFlags.Number, "number"],
        [ts.TypeFlags.Boolean, "boolean"],
        [ts.TypeFlags.Never, "never"]] as const) if (type.flags & flag) return text;
    if (type.getSymbol()?.name === "Date") return input ? "never" : "string";
    const reference = type as ts.TypeReference;
    const tuple = !!(reference.target?.objectFlags & ts.ObjectFlags.Tuple);
    if (["Array", "ReadonlyArray"].includes(type.getSymbol()?.name ?? "") || tuple) {
        const entries = checker.getTypeArguments(type as ts.TypeReference);
        if (tuple) {
            if (position === "query" && !entries.length) return "never";
            const flags = (reference.target as ts.TupleType).elementFlags;
            const parts = entries.map((entry, index) => {
                const text = wireType(checker, entry, node, next, input, "array");
                return flags[index] & ts.ElementFlags.Rest ? `...Array<${text}>` : !input && flags[index] & ts.ElementFlags.Optional ? `(${text})?` : text;
            });
            // Optional tuple syntax itself admits undefined in TS 4.9. For inputs,
            // enumerate valid shorter tuples without admitting undefined slots.
            const prefixes = input ? parts.flatMap((_part, index) => flags[index] & ts.ElementFlags.Optional
                ? [`[${parts.slice(0, index).join(", ")}]`] : []) : [];
            return [...prefixes, `[${parts.join(", ")}]`].join(" | ");
        }
        const element = wireType(checker, entries[0], node, next, input, "array");
        return position === "query" ? `[${element}, ...Array<${element}>]` : `Array<${element}>`;
    }
    if (!(type.flags & ts.TypeFlags.Object) && !type.isIntersection() || type.getCallSignatures().length) return "unknown";
    const properties = type.getProperties();
    const indexes = checker.getIndexInfosOfType(type);
    // Class instances and custom serialization do not promise an object wire shape.
    if (properties.some(property => property.name === "toJSON" || property.name.startsWith("__@"))) return "unknown";
    return `{ ${[
        ...properties.map(property => {
            const value = checker.getTypeOfSymbolAtLocation(property, node);
            const optional = property.flags & ts.SymbolFlags.Optional || !input && mayBeUndefined(value);
            return `${JSON.stringify(property.name)}${optional ? "?" : ""}: ${wireType(checker, value, node, next, input, position === "query" ? "query" : "property")};`;
        }),
        ...indexes.map(index => `[key: ${index.keyType.flags & ts.TypeFlags.Number ? "number" : "string"}]: ${wireType(checker, index.type, node, next, input, position === "query" ? "query" : "property")};`),
    ].join(" ")} }`;
}

function mayBeUndefined(type: ts.Type): boolean {
    return !!(type.flags & (ts.TypeFlags.Void | ts.TypeFlags.Undefined)) || type.isUnion() && type.types.some(mayBeUndefined);
}

/** Called between the initial and final check, using only TypeScript's static model. */
export function generateClientContracts(generated: TypegenResult, program: ts.Program): string {
    const checker = program.getTypeChecker();
    const lines = ["// Generated by Boring API. Do not edit. No server imports.", "export type ApiRoutes = {"];
    for (const route of generated.sources.routes) {
        const source = program.getSourceFile(route.file)!;
        const value = (name: string) => {
            const symbol = exported(checker, source, name);
            return symbol ? symbolType(checker, symbol, source) : undefined;
        };
        const schema = (name: string, side: "_input" | "_output") => {
            const property = value(name)?.getProperty(side);
            return property ? checker.getTypeOfSymbolAtLocation(property, source) : undefined;
        };
        const fields: string[] = [];
        const params = [...route.path.matchAll(/:([A-Za-z_][A-Za-z0-9_]*)/g)].map(match => match[1]);
        // Use input contracts before transformations, retaining literal/enum restrictions.
        const parameterSchema = schema("params", "_input");
        if (params.length) fields.push(`params: { ${params.map(name => {
            const property = parameterSchema?.getProperty(name);
            const type = property && checker.getTypeOfSymbolAtLocation(property, source);
            const text = type ? wireType(checker, type, source, new Set(), true) : "string | number";
            return `${JSON.stringify(name)}: ${text === "unknown" ? "string | number" : `Extract<(${text}), string | number | boolean>`};`;
        }).join(" ")} };`);
        for (const name of ["query", "body"] as const) {
            const type = schema(name, "_input");
            if (type && !(name === "body" && ["get", "head"].includes(route.method))) {
                const optional = type.isUnion() && type.types.some(member => member.flags & ts.TypeFlags.Undefined) ||
                    name === "query" && !!(type.flags & ts.TypeFlags.Object) && type.getProperties().every(property => property.flags & ts.SymbolFlags.Optional);
                const serializable = name === "query" ? " & Record<string, string | number | boolean | [string | number | boolean, ...Array<string | number | boolean>] | undefined>" : "";
                fields.push(`${name}${optional ? "?" : ""}: (${wireType(checker, type, source, new Set(), true, name)})${serializable};`);
            }
        }
        let output = schema("output", "_output");
        const envelope = value("envelope");
        // Without an output schema, an empty handler can finish with 204 before
        // the envelope runs. Keep its response unknown, including imperative writes.
        if (output && route.scope.envelope && !(envelope?.flags === ts.TypeFlags.BooleanLiteral && checker.typeToString(envelope) === "false")) {
            const hook = program.getSourceFile(route.scope.envelope)!;
            const handler = exported(checker, hook, "handler");
            const signatures = handler && symbolType(checker, handler, hook).getCallSignatures();
            // Selecting an overload requires the actual payload. The first
            // signature alone cannot describe the envelope's possible responses.
            output = signatures?.length === 1 ? signatures[0].getReturnType() : undefined;
            while (output && ["Promise", "PromiseLike"].includes(output.getSymbol()?.name ?? "")) {
                output = checker.getTypeArguments(output as ts.TypeReference)[0];
            }
            // A conditional envelope or imperative payload writes cannot be inferred safely.
            if (envelope && checker.typeToString(envelope) !== "true" || output && mayBeUndefined(output)) output = undefined;
        }
        const result = route.method === "head" ? "undefined" : output ? wireType(checker, output, source) : "unknown";
        lines.push(`    ${JSON.stringify(`${route.method.toUpperCase()} ${route.path}`)}: { input: { ${fields.join(" ")} }; output: ${result} };`);
    }
    lines.push("};", "");
    // generateTypes already validated this directory and rejected symlink ancestors.
    const file = generated.clientFile;
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, lines.join("\n"), { flag: "wx" });
    return file;
}
